/**
 * projects.js — centralny config projektów portfolio.
 *
 * JAK DODAĆ NOWY PROJEKT (3 kroki):
 *   1. Dodaj wpis do tablicy poniżej (pamiętaj o `slug` dla SEO URL)
 *   2. Utwórz plik: src/vue-portfolio/components/projects/ProjectNazwa.vue
 *   3. Gotowe — dynamic import działa automatycznie przez pole `component`
 *
 * slug: używany w URL /portfolio/{slug} (SEO-friendly)
 * drawerSide: 'left' | 'right' — z której strony wysuwa się panel
 */

export const projects = [
  {
    id: 'lgg',
    slug: 'lets-grow-gdansk',
    client: 'Semcore',
    title: "Let's Grow Gdańsk",
    shortDesc: '<strong>Kodowanie front-end z projektu graficznego</strong> na potrzeby wydarzenia organizowanego przez agencję Semcore – responsywna strona HTML/CSS z animacjami GSAP.',
    image: '/img/portfolio/lgg.webp',
    image2x: '/img/portfolio/lgg@2x.webp',
    imageAlt: "Let's Grow Gdańsk – responsywna strona HTML z animacjami GSAP dla agencji Semcore",
    url: 'https://lgg.cutme.pl/',
    skills: ['HTML/CSS', 'JavaScript', 'GSAP', 'Pixel Perfect'],
    drawerSide: 'left',
    component: () => import('./components/projects/ProjectLgg.vue'),
  },
  {
    id: 'mo',
    slug: 'marketing-opanowany',
    client: 'Jacek Kłosiński',
    title: 'Marketing Opanowany',
    shortDesc: 'Kompleksowe zlecenie na <strong>zakodowanie projektu graficznego z Figma</strong> oraz <strong>wdrożenie do WordPress</strong> z ACF i custom theme.',
    image: '/img/portfolio/mo.webp',
    image2x: '/img/portfolio/mo@2x.webp',
    imageAlt: 'Marketing Opanowany – kodowanie front-end Pixel Perfect i wdrożenie WordPress',
    url: 'https://marketingopanowany.pl',
    skills: ['WordPress', 'ACF', 'Figma', 'JavaScript', 'HTML/CSS'],
    drawerSide: 'right',
    component: () => import('./components/projects/ProjectMo.vue'),
  },
  {
    id: 'domlux',
    slug: 'domlux',
    client: 'Gophery',
    title: 'DomLux',
    shortDesc: '<strong>Pixel Perfect front-end</strong> – kodowanie projektu graficznego strony producenta ekskluzywnych mebli. Wdrożenie WordPress z dbałością o każdy detal.',
    image: '/img/portfolio/domlux.webp',
    image2x: '/img/portfolio/domlux@2x.webp',
    imageAlt: 'DomLux – Pixel Perfect kodowanie projektu graficznego i wdrożenie WordPress dla producenta mebli',
    url: 'https://domlux.cutme.pl',
    skills: ['HTML/CSS', 'Pixel Perfect', 'JavaScript', 'WordPress'],
    drawerSide: 'left',
    component: () => import('./components/projects/ProjectDomlux.vue'),
  },
  {
    id: 'karlex',
    slug: 'karlex',
    client: 'Gophery',
    title: 'Karlex',
    shortDesc: '<strong>Kodowanie PSD do HTML/CSS</strong> – zakodowanie szablonów z projektu graficznego dla firmy doradczej. Pixel Perfect, semantyczny kod HTML.',
    image: '/img/portfolio/kar.webp',
    image2x: '/img/portfolio/kar@2x.webp',
    imageAlt: 'Karlex – kodowanie PSD do HTML CSS, Pixel Perfect front-end dla firmy doradczej',
    url: 'https://karlex.cutme.pl',
    skills: ['HTML/CSS', 'Pixel Perfect', 'JavaScript'],
    drawerSide: 'right',
    component: () => import('./components/projects/ProjectKarlex.vue'),
  },
  {
    id: '4pharma',
    slug: '4pharma',
    client: 'Gophery',
    title: '4pharma',
    shortDesc: '<strong>Kodowanie front-end z animacjami GSAP</strong> i efektem parallax dla agencji doradztwa cyfrowego – dynamiczna, responsywna strona HTML.',
    image: '/img/portfolio/4pharma.webp',
    image2x: '/img/portfolio/4pharma@2x.webp',
    imageAlt: '4pharma – front-end z animacjami GSAP i efektem parallax, responsywna strona HTML',
    url: 'https://4pharma.cutme.pl',
    skills: ['HTML/CSS', 'GSAP', 'JavaScript', 'Parallax'],
    drawerSide: 'left',
    component: () => import('./components/projects/Project4pharma.vue'),
  },
  {
    id: 'mfd',
    slug: 'mfd',
    client: 'Dorian Karczmarzyk',
    title: 'MFD',
    shortDesc: '<strong>Kodowanie front-end i wdrożenie do WordPress</strong> dla start-upu w sektorze flot wagonów kolejowych. Animacje GSAP, semantyczny kod zoptymalizowany pod SEO.',
    image: '/img/portfolio/mfd.webp',
    image2x: '/img/portfolio/mfd@2x.webp',
    imageAlt: 'MFD – wdrożenie WordPress z animacjami GSAP dla startupu kolejowego',
    url: 'https://mfd.cutme.pl',
    skills: ['WordPress', 'GSAP', 'HTML/CSS', 'JavaScript'],
    drawerSide: 'right',
    component: () => import('./components/projects/ProjectMfd.vue'),
  },
  {
    id: 'flowair',
    slug: 'flowair',
    client: 'FlowAir',
    title: 'FlowAir',
    shortDesc: '<strong>Pixel Perfect front-end</strong> – kodowanie projektu z filmami poklatkowym, efektem parallax i dedykowaną galerią. Animacje GSAP, responsywna strona HTML.',
    image: '/img/portfolio/flowair.webp',
    image2x: '/img/portfolio/flowair@2x.webp',
    imageAlt: 'FlowAir – Pixel Perfect HTML CSS z animacjami GSAP, video i efektem parallax',
    url: 'https://flowair.cutme.pl',
    skills: ['HTML/CSS', 'GSAP', 'JavaScript', 'Pixel Perfect'],
    drawerSide: 'left',
    component: () => import('./components/projects/ProjectFlowair.vue'),
  },
  {
    id: 'leasingujesz',
    slug: 'leasingujesz',
    client: 'Gophery',
    title: 'Leasingujesz',
    shortDesc: '<strong>Kodowanie layoutu HTML CSS z projektu graficznego</strong> dla portalu porównywania ofert leasingowych. Pixel Perfect, responsywna strona internetowa.',
    image: '/img/portfolio/lea.webp',
    image2x: '/img/portfolio/lea@2x.webp',
    imageAlt: 'Leasingujesz – kodowanie layoutu HTML CSS Pixel Perfect, portal porównywania leasingu',
    url: 'https://leasingujesz.cutme.pl/1.0-index.html',
    skills: ['HTML/CSS', 'Pixel Perfect', 'JavaScript'],
    drawerSide: 'right',
    component: () => import('./components/projects/ProjectLeasingujesz.vue'),
  },
  {
    id: 'ftfund',
    slug: 'ft-fund',
    title: 'FT Fund',
    shortDesc: '<strong>Kodowanie i wdrożenie do WordPress</strong> projektu landpage firmy pożyczkowej – custom theme, semantyczny HTML, responsywna strona.',
    image: '/img/portfolio/ftf.webp',
    image2x: '/img/portfolio/ftf@2x.webp',
    imageAlt: 'FT Fund – wdrożenie WordPress, custom theme dla firmy pożyczkowej',
    url: 'https://ftfund.cutme.pl',
    skills: ['WordPress', 'HTML/CSS'],
    drawerSide: 'left',
    component: () => import('./components/projects/ProjectFtfund.vue'),
  },
  {
    id: '126',
    slug: '126-marek',
    client: 'Engram',
    title: '126 marek',
    shortDesc: '<strong>Kodowanie front-end z projektu graficznego</strong> – semantyczny HTML/CSS z animacjami GSAP. Pixel Perfect, responsywna realizacja dla agencji Engram.',
    image: '/img/portfolio/126.webp',
    image2x: '/img/portfolio/126@2x.webp',
    imageAlt: '126 marek – kodowanie front-end Pixel Perfect z animacjami GSAP dla agencji Engram',
    url: 'http://126.cutme.pl',
    skills: ['HTML/CSS', 'Pixel Perfect', 'JavaScript', 'GSAP'],
    drawerSide: 'right',
    component: () => import('./components/projects/Project126.vue'),
  },
  {
    id: 'metoda',
    slug: 'metoda-teczowki',
    client: 'Jacek Kłosiński',
    title: 'Metoda Tęczówki',
    shortDesc: '<strong>Kodowanie front-end z animacjami GSAP</strong> – nagrodzony projekt wyróżniony przez CSS Awards. Interaktywny UX, nowoczesne animacje CSS i JavaScript.',
    image: '/img/portfolio/met.webp',
    image2x: '/img/portfolio/met@2x.webp',
    imageAlt: 'Metoda Tęczówki – nagradzana strona front-end z animacjami GSAP, wyróżnienie CSS Awards',
    url: 'https://klosinski.net/metodateczowki/',
    skills: ['HTML/CSS', 'GSAP', 'JavaScript', 'CSS Awards'],
    drawerSide: 'left',
    component: () => import('./components/projects/ProjectMetoda.vue'),
  },
  {
    id: 'ltl_biobank',
    slug: 'ltl-biobank',
    client: 'Quar Studio',
    title: 'LTL / Biobank',
    shortDesc: '<strong>Kodowanie Figma do WordPress</strong> – wdrożenie dwóch projektów graficznych jako responsywnych stron WordPress z ACF i animacjami GSAP.',
    image: '/img/portfolio/ltl.webp',
    image2x: '/img/portfolio/ltl@2x.webp',
    imageAlt: 'LTL i Biobank – kodowanie Figma do WordPress, wdrożenie dwóch projektów graficznych z ACF',
    url: 'https://ltl.cutme.pl/',
    skills: ['WordPress', 'HTML/CSS', 'JavaScript', 'GSAP', 'ACF'],
    drawerSide: 'right',
    component: () => import('./components/projects/ProjectLtlBiobank.vue'),
  },
  {
    id: 'quar',
    slug: 'quar-studio',
    title: 'Quar Studio',
    shortDesc: '<strong>Kodowanie i wdrożenie do WordPress</strong> – portfolio projektanta grafika UX/UI. Custom theme WordPress, responsywna strona Pixel Perfect.',
    image: '/img/portfolio/qua.webp',
    image2x: '/img/portfolio/qua@2x.webp',
    imageAlt: 'Quar Studio – wdrożenie WordPress portfolio projektanta UX/UI, custom theme',
    url: 'http://qua.cutme.pl/',
    skills: ['WordPress', 'HTML/CSS', 'JavaScript'],
    drawerSide: 'left',
    component: () => import('./components/projects/ProjectQuar.vue'),
  },
  {
    id: 'brandhub',
    slug: 'brandhub',
    title: 'BrandHub',
    shortDesc: '<strong>Pixel Perfect front-end</strong> – kodowanie projektu graficznego dla agencji brandingowej BrandHub. Animacje CSS, semantyczny HTML, responsywna strona.',
    image: '/img/portfolio/brandhub.webp',
    image2x: '/img/portfolio/brandhub@2x.webp',
    imageAlt: 'BrandHub – Pixel Perfect front-end dla agencji brandingowej, animacje CSS i semantyczny HTML',
    url: 'https://brandhub.cutme.pl/',
    skills: ['HTML/CSS', 'Pixel Perfect', 'JavaScript', 'GSAP'],
    drawerSide: 'right',
    component: () => import('./components/projects/ProjectBrandhub.vue'),
  },
];

export const projects_en = [
  {
    id: 'lgg',
    slug: 'lets-grow-gdansk',
    client: 'Semcore',
    title: "Let's Grow Gdańsk",
    shortDesc: '<strong>Front-end coding from graphic design</strong> for an event organized by Semcore agency – responsive HTML/CSS page with GSAP animations.',
    image: '/img/portfolio/lgg.webp',
    image2x: '/img/portfolio/lgg@2x.webp',
    imageAlt: "Let's Grow Gdańsk – responsive HTML page with GSAP animations for Semcore agency",
    url: 'https://lgg.cutme.pl/',
    skills: ['HTML/CSS', 'JavaScript', 'GSAP', 'Pixel Perfect'],
    drawerSide: 'left',
    component: () => import('./components/projects/en/ProjectLggEn.vue'),
  },
  {
    id: 'mo',
    slug: 'marketing-opanowany',
    client: 'Jacek Kłosiński',
    title: 'Marketing Opanowany',
    shortDesc: 'Full-scope project: <strong>coding from Figma design</strong> and <strong>WordPress implementation</strong> with ACF and custom theme.',
    image: '/img/portfolio/mo.webp',
    image2x: '/img/portfolio/mo@2x.webp',
    imageAlt: 'Marketing Opanowany – Pixel Perfect front-end coding and WordPress implementation',
    url: 'https://marketingopanowany.pl',
    skills: ['WordPress', 'ACF', 'Figma', 'JavaScript', 'HTML/CSS'],
    drawerSide: 'right',
    component: () => import('./components/projects/en/ProjectMoEn.vue'),
  },
  {
    id: 'domlux',
    slug: 'domlux',
    client: 'Gophery',
    title: 'DomLux',
    shortDesc: '<strong>Pixel Perfect front-end</strong> – coding a graphic design for a luxury furniture manufacturer. WordPress implementation with attention to every detail.',
    image: '/img/portfolio/domlux.webp',
    image2x: '/img/portfolio/domlux@2x.webp',
    imageAlt: 'DomLux – Pixel Perfect front-end coding and WordPress implementation for luxury furniture brand',
    url: 'https://domlux.cutme.pl',
    skills: ['HTML/CSS', 'Pixel Perfect', 'JavaScript', 'WordPress'],
    drawerSide: 'left',
    component: () => import('./components/projects/en/ProjectDomluxEn.vue'),
  },
  {
    id: 'karlex',
    slug: 'karlex',
    client: 'Gophery',
    title: 'Karlex',
    shortDesc: '<strong>PSD to HTML/CSS coding</strong> – converting graphic design templates to semantic, Pixel Perfect HTML for a consulting firm.',
    image: '/img/portfolio/kar.webp',
    image2x: '/img/portfolio/kar@2x.webp',
    imageAlt: 'Karlex – PSD to HTML CSS coding, Pixel Perfect front-end for a consulting firm',
    url: 'https://karlex.cutme.pl',
    skills: ['HTML/CSS', 'Pixel Perfect', 'JavaScript'],
    drawerSide: 'right',
    component: () => import('./components/projects/en/ProjectKarlexEn.vue'),
  },
  {
    id: '4pharma',
    slug: '4pharma',
    client: 'Gophery',
    title: '4pharma',
    shortDesc: '<strong>Front-end coding with GSAP animations</strong> and parallax effect for a digital advisory agency – dynamic, responsive HTML page.',
    image: '/img/portfolio/4pharma.webp',
    image2x: '/img/portfolio/4pharma@2x.webp',
    imageAlt: '4pharma – front-end with GSAP animations and parallax effect, responsive HTML page',
    url: 'https://4pharma.cutme.pl',
    skills: ['HTML/CSS', 'GSAP', 'JavaScript', 'Parallax'],
    drawerSide: 'left',
    component: () => import('./components/projects/en/Project4pharmaEn.vue'),
  },
  {
    id: 'mfd',
    slug: 'mfd',
    client: 'Dorian Karczmarzyk',
    title: 'MFD',
    shortDesc: '<strong>Front-end coding and WordPress implementation</strong> for a railway fleet startup. GSAP animations, semantic SEO-optimized code.',
    image: '/img/portfolio/mfd.webp',
    image2x: '/img/portfolio/mfd@2x.webp',
    imageAlt: 'MFD – WordPress implementation with GSAP animations for a railway startup',
    url: 'https://mfd.cutme.pl',
    skills: ['WordPress', 'GSAP', 'HTML/CSS', 'JavaScript'],
    drawerSide: 'right',
    component: () => import('./components/projects/en/ProjectMfdEn.vue'),
  },
  {
    id: 'flowair',
    slug: 'flowair',
    client: 'FlowAir',
    title: 'FlowAir',
    shortDesc: '<strong>Pixel Perfect front-end</strong> – coding a design with time-lapse video, parallax effect and custom gallery. GSAP animations, responsive HTML.',
    image: '/img/portfolio/flowair.webp',
    image2x: '/img/portfolio/flowair@2x.webp',
    imageAlt: 'FlowAir – Pixel Perfect HTML CSS with GSAP animations, video and parallax effect',
    url: 'https://flowair.cutme.pl',
    skills: ['HTML/CSS', 'GSAP', 'JavaScript', 'Pixel Perfect'],
    drawerSide: 'left',
    component: () => import('./components/projects/en/ProjectFlowairEn.vue'),
  },
  {
    id: 'leasingujesz',
    slug: 'leasingujesz',
    client: 'Gophery',
    title: 'Leasingujesz',
    shortDesc: '<strong>HTML CSS layout coding from graphic design</strong> for a leasing comparison portal. Pixel Perfect, responsive web design.',
    image: '/img/portfolio/lea.webp',
    image2x: '/img/portfolio/lea@2x.webp',
    imageAlt: 'Leasingujesz – Pixel Perfect HTML CSS layout coding, leasing comparison portal',
    url: 'https://leasingujesz.cutme.pl/1.0-index.html',
    skills: ['HTML/CSS', 'Pixel Perfect', 'JavaScript'],
    drawerSide: 'right',
    component: () => import('./components/projects/en/ProjectLeasingujeszEn.vue'),
  },
  {
    id: 'ftfund',
    slug: 'ft-fund',
    title: 'FT Fund',
    shortDesc: '<strong>Coding and WordPress implementation</strong> of a landing page for a loan company – custom theme, semantic HTML, responsive website.',
    image: '/img/portfolio/ftf.webp',
    image2x: '/img/portfolio/ftf@2x.webp',
    imageAlt: 'FT Fund – WordPress implementation, custom theme for a loan company',
    url: 'https://ftfund.cutme.pl',
    skills: ['WordPress', 'HTML/CSS'],
    drawerSide: 'left',
    component: () => import('./components/projects/en/ProjectFtfundEn.vue'),
  },
  {
    id: '126',
    slug: '126-marek',
    client: 'Engram',
    title: '126 marek',
    shortDesc: '<strong>Front-end coding from graphic design</strong> – semantic HTML/CSS with GSAP animations. Pixel Perfect, responsive implementation for Engram agency.',
    image: '/img/portfolio/126.webp',
    image2x: '/img/portfolio/126@2x.webp',
    imageAlt: '126 marek – Pixel Perfect front-end with GSAP animations for Engram agency',
    url: 'http://126.cutme.pl',
    skills: ['HTML/CSS', 'Pixel Perfect', 'JavaScript', 'GSAP'],
    drawerSide: 'right',
    component: () => import('./components/projects/en/Project126En.vue'),
  },
  {
    id: 'metoda',
    slug: 'metoda-teczowki',
    client: 'Jacek Kłosiński',
    title: 'Metoda Tęczówki',
    shortDesc: '<strong>Front-end coding with GSAP animations</strong> – award-winning project honored by CSS Awards. Interactive UX, modern CSS and JavaScript animations.',
    image: '/img/portfolio/met.webp',
    image2x: '/img/portfolio/met@2x.webp',
    imageAlt: 'Metoda Teczowki – award-winning front-end with GSAP animations, CSS Awards distinction',
    url: 'https://klosinski.net/metodateczowki/',
    skills: ['HTML/CSS', 'GSAP', 'JavaScript', 'CSS Awards'],
    drawerSide: 'left',
    component: () => import('./components/projects/en/ProjectMetodaEn.vue'),
  },
  {
    id: 'ltl_biobank',
    slug: 'ltl-biobank',
    client: 'Quar Studio',
    title: 'LTL / Biobank',
    shortDesc: '<strong>Figma to WordPress coding</strong> – implementation of two graphic designs as responsive WordPress sites with ACF and GSAP animations.',
    image: '/img/portfolio/ltl.webp',
    image2x: '/img/portfolio/ltl@2x.webp',
    imageAlt: 'LTL and Biobank – Figma to WordPress coding, two graphic design implementations with ACF',
    url: 'https://ltl.cutme.pl/',
    skills: ['WordPress', 'HTML/CSS', 'JavaScript', 'GSAP', 'ACF'],
    drawerSide: 'right',
    component: () => import('./components/projects/en/ProjectLtlBiobankEn.vue'),
  },
  {
    id: 'quar',
    slug: 'quar-studio',
    title: 'Quar Studio',
    shortDesc: '<strong>Coding and WordPress implementation</strong> – portfolio website for a UX/UI graphic designer. Custom WordPress theme, Pixel Perfect responsive design.',
    image: '/img/portfolio/qua.webp',
    image2x: '/img/portfolio/qua@2x.webp',
    imageAlt: 'Quar Studio – WordPress portfolio for UX/UI designer, custom theme',
    url: 'http://qua.cutme.pl/',
    skills: ['WordPress', 'HTML/CSS', 'JavaScript'],
    drawerSide: 'left',
    component: () => import('./components/projects/en/ProjectQuarEn.vue'),
  },
  {
    id: 'brandhub',
    slug: 'brandhub',
    title: 'BrandHub',
    shortDesc: '<strong>Pixel Perfect front-end</strong> – coding a graphic design for BrandHub branding agency. CSS animations, semantic HTML, responsive website.',
    image: '/img/portfolio/brandhub.webp',
    image2x: '/img/portfolio/brandhub@2x.webp',
    imageAlt: 'BrandHub – Pixel Perfect front-end for a branding agency, CSS animations and semantic HTML',
    url: 'https://brandhub.cutme.pl/',
    skills: ['HTML/CSS', 'Pixel Perfect', 'JavaScript', 'GSAP'],
    drawerSide: 'right',
    component: () => import('./components/projects/en/ProjectBrandhubEn.vue'),
  },
];
